### ISSUE TITLE
Game Crash: java.util.MissingFormatArgumentException: Format specifier '%s'

### ISSUE THREAD

**Issue by WimpieRatte** [fabbe50/LangSplit#8]
I loaded the game, opened my inventory, then saw a quickly-displaying error about EMI, then the game crashed.
Here's the crash report.

Stacktrace:
	at java.base/java.util.Formatter.format(Formatter.java:2688)
	at java.base/java.util.Formatter.format(Formatter.java:2625)
	at java.base/java.lang.String.format(String.java:4143)
	at com.fabbe50.langsplit.common.Langsplit.lambda$handleTooltipEvent$0(Langsplit.java:87)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy212.append(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$6(EventHandlerImpl.java:60)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37)
	at net.minecraft.class_1799.handler$dpg001$fabric-item-api-v1$getTooltip(class_1799.java:9162)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_481.method_25409(class_481.java:731)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_481.method_25394(class_481.java:692)

[crash-2023-05-07_21.40.19-client.txt](https://github.com/fabbe50/languagesplitter/files/11415859/crash-2023-05-07_21.40.19-client.txt)

**Comment by fabbe50** [comment]
Uploaded a hotfix for this. Let me know if there's any issues, otherwise I'll close this issue soon.

https://modrinth.com/mod/langsplit/version/2.1.5.2-beta
